theme: jekyll-theme-architect
title: Liang Zhang
description: Liang Zhang, founder and PMC Chair of Apache ShardingSphere and ElasticJob<br />张亮，Apache ShardingSphere，ElasticJob 创始人 & 项目管理委员会主席
show_downloads: false
